"""
Obsidian Bridge - file-based incident knowledge base for NEXUS SCADA.

Every high-severity diagnosis can be persisted as a markdown file in a
local Obsidian vault, giving operators a human-readable, linkable,
fully-offline incident history (IEC 62443-friendly: no cloud, no DB).

Design rules:
- fire-and-forget: any failure inside must NEVER propagate to the agent
- rotation: Incidents/ is capped, oldest files archive automatically
- no dependencies beyond the standard library
"""

import shutil
import time
from datetime import datetime
from pathlib import Path

VAULT_DIR = Path(__file__).resolve().parent / "data" / "scada_vault"
INCIDENTS_DIR = VAULT_DIR / "Incidents"
ARCHIVE_DIR = INCIDENTS_DIR / "archive"
ROTATION_LIMIT = 500


def _rotate_if_needed() -> None:
    """Move oldest incident files to archive when the cap is exceeded."""
    if not INCIDENTS_DIR.exists():
        return
    incidents = [p for p in INCIDENTS_DIR.glob("*.md") if p.is_file()]
    if len(incidents) <= ROTATION_LIMIT:
        return
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    incidents.sort(key=lambda p: p.stat().st_mtime)
    overflow = len(incidents) - ROTATION_LIMIT
    for p in incidents[:overflow]:
        shutil.move(str(p), str(ARCHIVE_DIR / p.name))


def log_incident(
    equipment_ids: list,
    fault_type: str,
    diagnosis: str,
    recommended_action: str,
    severity: str = "MEDIUM",
    source: str = "ai_engine",
) -> str:
    """
    Write one incident report into the vault. Returns the file path,
    or an empty string on any failure (never raises).
    """
    try:
        INCIDENTS_DIR.mkdir(parents=True, exist_ok=True)
        now = datetime.now()
        machine_links = ", ".join(f"[[{eq}]]" for eq in equipment_ids) or "SYSTEM"
        standard_link = f"[[ANSI-{fault_type}]]" if fault_type.startswith("ANSI-") else fault_type

        filename = f"{now.strftime('%Y%m%d_%H%M%S')}_{equipment_ids[0] if equipment_ids else 'SYSTEM'}.md"
        filepath = INCIDENTS_DIR / filename

        content = f"""---
timestamp: {now.isoformat()}
severity: {severity}
equipment: {machine_links}
fault: {standard_link}
source: {source}
---

# Industrial Incident Report (auto-generated by NEXUS AI)

**Time:** {now.strftime('%Y-%m-%d %H:%M:%S')}  
**Severity:** {severity}  
**Equipment:** {machine_links}  
**Fault class:** {standard_link}

## Diagnosis
{diagnosis}

## Recommended Action
{recommended_action}

## Linked Equipment
"""
        for eq in equipment_ids:
            content += f"- [[{eq}]]\n"

        filepath.write_text(content, encoding="utf-8")
        _rotate_if_needed()
        return str(filepath)

    except Exception as e:  # fire-and-forget: swallow everything
        print(f"[OBSIDIAN] incident logging skipped (non-fatal): {e}")
        return ""


if __name__ == "__main__":
    path = log_incident(
        ["STP-01"], "ANSI-38",
        "Theta exceeded 100% for 5 consecutive polls - sustained thermal overload.",
        "inspect_process",
        severity="HIGH",
    )
    print(f"[TEST] incident written to: {path}")
